rename casefile to prevent conflict
Error: casereport.CaseReport.casefile: (models.E006) The field 'casefile' clashes with the field 'casefile' from model 'casereport.crdbbase'.